name: CI/CD
on:
  pull_request:
    branches: [ main, ai ]
env:
  PY_COLORS: "1"
permissions:
  contents: read
  checks: write
  pull-requests: write
  id-token: write
jobs:
  black:
    name: Black Formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "24.2.0"
  ruff:
    name: Ruff Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "."
          version: "0.1.12"